<?php

/**
 * Implements hook_menu().
 */

function mapping_menu() {
  return array(
    'map-list' => array(
      'page callback' => 'mapping_map_list',
      'title' => 'Map List',
      'access arguments' => array('access content'),
    ),
    'map-list/render' => array(
      'page callback' => 'mapping_map_render',
      'title' => 'Map Render',
      'access arguments' => array('access content'),
    ),
  );
}

function mapping_map_list() {
  $type = drupal_container()->get('plugin.manager.mapping');
  dpm($type->getDefinitions());
  return "HI";
}

function mapping_map_render() {
  $type = drupal_container()->get('plugin.manager.mapping');
  $map_plugin = $type->createInstance('map_basic');
  return $map_plugin->build();
}
